### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by erezfree29**
page completed attempting to pass linters tests

### CODE REVIEW

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello! Great work on your project! 🥇 However there are some changes that need to be implemented.

Changes required 🔴 

- [ ] There are several parts of the webpage that are not well positioned on your project (Check images for reference) please implement a complete clone, I recommend you to open your project and the original side by side and copy every element.

img1
img2

For future projects 🟡 

- [ ] Remember that your commit messages need to be descriptive and meaningful Repeated commit like "edited html" "fixing erros" do not fulfill this requirement. You might want to Rebase your commits or merge every repeated comment but for example replace  "edited html" with "edited html footer to fix the positioning" You might want to read about: https://git-scm.com/docs/git-rebase


After making the requested changes please resubmit your project for another review.

Cheers!

Code review by Mario Enrique Delgado Naranjo

**Comment by erezfree29** [comment]
Hello my code looks ok when I open it in fire fox 
Screenshot
it does however does not look well-positioned on git pages and I did not determine the reason.

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

I could not review the changes you have implemented, because the link to your live demo isn't working. 

Here is the [link](https://erezfree29.github.io/new-york-times/) you provided.
https://erezfree29.github.io/new-york-times/

Also, use [mark down](https://guides.github.com/features/mastering-markdown/) to format what you are writing on your README. 

#### Ensure you fix the issue, then submit another form for code review

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Comment by erezfree29** [comment]
did not show well on git hub pages and when I inspected the file the css has not been updated there

**Pull request closed without merging**
